### ISSUE TITLE
Auto-bonus-gigs bump

### ISSUE THREAD

**Issue by merickson** [SpiderOak/netkes#190]
One of our Private Cloud customers needs space restrictions for their users, however they're running into bugs with trying to upload too much. In conjunction with deploying storage server fixes to avoid signaling the out of space popup too often, we need to be able to grant the user some additional space temporarily so they can clear it out.

We should have a button in the Management Console that increases the storage limit for the user by 5 GB for 72 hours. This button should only exist for users **not** on an unlimited plan.

The workflow would be:
1. Admin hits button on the MC, user gets 5 additional bonus GBs, row inserted in the DB with a timestamp.
1. Hourly cron job runs, and any users with those bonus GBs with timestamps older than 72 hours get adjusted back down.

**Comment by bdzim** [comment]
Should we only show the button for users who are over or nearly over their space?

**Comment by brian-emery** [comment]
I think it would be safer to show the button for all users. Tony is describing situations where the client is allowing files to be added to the queue that will not fit within the user's space limit. For example, several files are added to the queue and one of them is 1.7GB (the user's allotment is 2GB). The other files upload without a problem but then the queue stops uploading when it hits the 1.7GB file. The actual amount of uploaded data is still far from their limit, but they still need a temporary space increase to fix the problem. I'm not 100% this is accurate, but it is how Tony describes it.

**Comment by bdzim** [comment]
OK. How about I show the button for all user not on an unlimited plan?

**Comment by reneelynn** [comment]
@brian-emery the situation you describe would happen in one of two scenarios: 1) user has "space calculations" disabled. 2) User clicks "save" before allowing space calculations to finalize.

**Comment by bdzim** [comment]
Any thoughts on what to call the button? I'm calling it "Bump Space" at the moment.
