### ISSUE TITLE
Paging issue on Shares page

### ISSUE THREAD

**Issue by brian-emery** [SpiderOak/netkes#193]
A privatecloud customer reports that the  Shares tab doesn't allow navigation to anything beyond the first page of Shares.

**Comment by bdzim** [comment]
Shares are actually fetched per user. We fetch the shares for 10 users per page. So when testing you'll need at least 10 users with shares. No amount of shares for a single user will cause it to paginate.

**Comment by reneelynn** [comment]
I can navigate to the next page of shares in 2.1.10. I have 13 shares from 12 unique end users.
