### ISSUE TITLE
3.3.0 Network Disconnect Errors

### ISSUE THREAD

**Issue by rebeccawatson** [SpiderOak/netkes#197]
- restarting/rebooting my Unicorn Ranch VM fixes this, so this an API-side thing
- log into an account on the blue or orange app
- stay logged in:true, set a passcode
- exit out of app completely
- restart, passcode screen pops up
- 401 network error immediately, but then goes away and you're able to navigate normally.

https://github.com/SpiderOak/SpiderOakMobileClient/issues/689

**Comment by devgeeks** [comment]
if it's an API side thing, not much I can do...
