### ISSUE TITLE
Minor display issue on user detail pages for certain customers.

### ISSUE THREAD

**Issue by brian-emery** [SpiderOak/netkes#198]
Certain privatecloud customers have a minor display issue on user detail pages in version 2.1.9. See:

https://treehouse.spideroak.com/pandora/ticket/6261

**Comment by reneelynn** [comment]
I don't see this in 2.1.10 but leaving open until we verify with the affected customers.

**Comment by brian-emery** [comment]
Confirmed. Fixed in 2.1.10.
