### ISSUE TITLE
Improve reliability of creating new users through ldap

### ISSUE THREAD

**Issue by bdzim** [SpiderOak/netkes#206]
When creating new users through ldap we create the user and then fetch the user data. This will occasionally fail. We catch that failure and try again, but even that can possibly fail. The accounts api has been updated to return the user data through the create user call. Fetching the user data this way should improve reliability and make creating users faster.

**Comment by reneelynn** [comment]
Not sure whether this has been worked on or not but adding users via LDAP has been speedy and effective today.

**Comment by bdzim** [comment]
It has been worked on. As long as adding users via LDAP is working then this is working.
