### ISSUE TITLE
Default Group Name

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/netkes#223]
## Description 
Default Group should be name after company. No Default group names should have management username.

## Actual result 
no group named BenIT... is this testcase deprecated?

## Other information 
Reported by: Renee Jackson 

Test case number: TC47 

Test run: [http://spideroak.testlodge.com/projects/2632/runs/155678?tab=2&run_section_id=97703#executed_case_7722365](http://spideroak.testlodge.com/projects/2632/runs/155678?tab=2&run_section_id=97703#executed_case_7722365)

**Comment by bdzim** [comment]
Can you walk me through the steps you used to get this result?

And what do you mean by a default group?

For a new account there should be a group named after the company. But that group can be changed or deleted.

**Comment by reneelynn** [comment]
This is a result from testing on your MC - I simply noticed there was no group named after the company, but it is possible you've simply changed/deleted that group. I'll update the testcase to clarify language.
