### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/netkes#225]
## Description 
The Users section of the management console is where you can interact with the users provisioned for your SpiderOak Blue service.

## Steps to reproduce issue 
Use the Search bar to look up users by name, then by e-mail.

## Actual result 
When you search a category that doesn't exist it defaults back to the same screen as when you have no users added yet.

## Other information 
Reported by: Renee Jackson 

Test case number: TC10 

Test run: [http://spideroak.testlodge.com/projects/2632/runs/155678?tab=2&run_section_id=97703#executed_case_7722368](http://spideroak.testlodge.com/projects/2632/runs/155678?tab=2&run_section_id=97703#executed_case_7722368)

**Comment by reneelynn** [comment]
This same result happens when you use Reports for a category that returns no results.

**Comment by bdzim** [comment]
What should we show if there are users, but there's nothing to show for a search? 

"No users found"?

**Comment by reneelynn** [comment]
I think that would be clearer.

**Comment by reneelynn** [comment]
![screen shot 2015-07-20 at 8 41 27 am](https://cloud.githubusercontent.com/assets/3867179/8777882/69873180-2ec0-11e5-8ab0-dbfb7b0c16ea.png)

**Comment by bdzim** [comment]
Fixed in beta 2.
